/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import clases.Cancion;
import clases.ListaCanciones;
import clases.MP3;
import clases.NodoD;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import dom.CancionDOM;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author Miguel
 */
public class Principal extends javax.swing.JFrame {

    private FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de música", "mp3");
    private FileNameExtensionFilter filterOpen = new FileNameExtensionFilter("Archivos de texto", "xml");
    MP3 myMP3;
    private List<String> listaReproduccion;
    ListaCanciones lista = new ListaCanciones();
    Cancion cancion;
    TextAutoCompleter textAutoAcompleter;
    private Cancion cancionXML;
    private CancionDOM cancionDOM;
    int numeroCaracteres = 0;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../img/iTunes_48px.png")).getImage());
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        txtTitulo2 = new javax.swing.JTextField();
        pnlContenedor = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        btnLista1 = new javax.swing.JButton();
        btnAbrir1 = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        pnlReproduccion = new javax.swing.JTabbedPane();
        pnlMiMusica = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstNombres = new javax.swing.JList<>();
        btnBorrar = new javax.swing.JButton();
        pnlMiMusica1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstNombres1 = new javax.swing.JList<>();
        btnBorrar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtTitulo = new javax.swing.JTextField();
        lblArtista2 = new javax.swing.JLabel();
        lblAlbum2 = new javax.swing.JLabel();
        lblGenero2 = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox<>();
        lblRuta2 = new javax.swing.JLabel();
        btnSeleccionar2 = new javax.swing.JToggleButton();
        txtAlbum = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        lblGenero4 = new javax.swing.JLabel();
        txtArtista = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        txtRuta = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        pnlReproducciendo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblTitulo3 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        txtCancionReproducciendo = new javax.swing.JTextField();
        btnReproducirPause = new javax.swing.JButton();
        btnIrAnterior = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnIrPrimero = new javax.swing.JButton();
        btnIrAnterior1 = new javax.swing.JButton();
        imagen4 = new javax.swing.JLabel();
        imagen1 = new javax.swing.JLabel();
        imagen2 = new javax.swing.JLabel();
        imagen3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnCambiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        txtTitulo2.setBackground(new java.awt.Color(36, 47, 65));
        txtTitulo2.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        txtTitulo2.setBorder(null);
        txtTitulo2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTitulo2FocusLost(evt);
            }
        });
        txtTitulo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTitulo2MouseClicked(evt);
            }
        });
        txtTitulo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitulo2ActionPerformed(evt);
            }
        });
        txtTitulo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTitulo2KeyTyped(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlContenedor.setBackground(new java.awt.Color(255, 255, 255));
        pnlContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        pnlContenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(0, 18, 50));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowBottomShadow(false);
        pnlMenu.setBorder(dropShadowBorder1);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-user.png"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Mi música");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnLista.setBackground(new java.awt.Color(0, 0, 0));
        btnLista.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnLista.setForeground(new java.awt.Color(255, 255, 255));
        btnLista.setText("Crear nueva canción");
        btnLista.setBorder(null);
        btnLista.setContentAreaFilled(false);
        btnLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLista.setOpaque(true);
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Créditos");
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        btnLista1.setBackground(new java.awt.Color(0, 0, 0));
        btnLista1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnLista1.setForeground(new java.awt.Color(255, 255, 255));
        btnLista1.setText("Reproducciendo");
        btnLista1.setBorder(null);
        btnLista1.setContentAreaFilled(false);
        btnLista1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLista1.setOpaque(true);
        btnLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLista1ActionPerformed(evt);
            }
        });

        btnAbrir1.setBackground(new java.awt.Color(0, 0, 0));
        btnAbrir1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        btnAbrir1.setForeground(new java.awt.Color(255, 255, 255));
        btnAbrir1.setText("Abrir lista");
        btnAbrir1.setBorder(null);
        btnAbrir1.setContentAreaFilled(false);
        btnAbrir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbrir1.setOpaque(true);
        btnAbrir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLista, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnLista1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAbrir1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLista, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLista1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAbrir1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnlContenedor.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-menu.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono-menu1.png"))); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        pnlContenedor.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, 52));

        pnlReproduccion.setBackground(new java.awt.Color(36, 47, 65));
        pnlReproduccion.setToolTipText("");
        pnlReproduccion.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        pnlMiMusica.setBackground(new java.awt.Color(36, 47, 65));

        lstNombres.setBackground(new java.awt.Color(153, 153, 153));
        lstNombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstNombresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstNombres);

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Trash_32px.png"))); // NOI18N
        btnBorrar.setToolTipText("Eliminar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        pnlMiMusica1.setBackground(new java.awt.Color(36, 47, 65));

        lstNombres1.setBackground(new java.awt.Color(153, 153, 153));
        lstNombres1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstNombres1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstNombres1);

        javax.swing.GroupLayout pnlMiMusica1Layout = new javax.swing.GroupLayout(pnlMiMusica1);
        pnlMiMusica1.setLayout(pnlMiMusica1Layout);
        pnlMiMusica1Layout.setHorizontalGroup(
            pnlMiMusica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMiMusica1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(649, Short.MAX_VALUE))
        );
        pnlMiMusica1Layout.setVerticalGroup(
            pnlMiMusica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMiMusica1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        btnBorrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Play_32px.png"))); // NOI18N
        btnBorrar1.setToolTipText("Reproduccir");
        btnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMiMusicaLayout = new javax.swing.GroupLayout(pnlMiMusica);
        pnlMiMusica.setLayout(pnlMiMusicaLayout);
        pnlMiMusicaLayout.setHorizontalGroup(
            pnlMiMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMiMusicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMiMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(649, Short.MAX_VALUE))
            .addGroup(pnlMiMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMiMusicaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMiMusica1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlMiMusicaLayout.setVerticalGroup(
            pnlMiMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMiMusicaLayout.createSequentialGroup()
                .addGroup(pnlMiMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMiMusicaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMiMusicaLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(pnlMiMusicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMiMusicaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlMiMusica1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pnlReproduccion.addTab("Mi música", pnlMiMusica);

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));

        lblTitulo2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo2.setText("Titulo:");

        txtTitulo.setBackground(new java.awt.Color(36, 47, 65));
        txtTitulo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(255, 255, 0));
        txtTitulo.setBorder(null);
        txtTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTituloFocusLost(evt);
            }
        });
        txtTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTituloMouseClicked(evt);
            }
        });
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTituloKeyTyped(evt);
            }
        });

        lblArtista2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblArtista2.setForeground(new java.awt.Color(255, 255, 255));
        lblArtista2.setText("Artista:");

        lblAlbum2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblAlbum2.setForeground(new java.awt.Color(255, 255, 255));
        lblAlbum2.setText("Albúm:");

        lblGenero2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblGenero2.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero2.setText("Año:");

        cmbGenero.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alternativa", "Bachata", "Balada", "Ballenato", "Banda", "Clasica", "Electronica", "Norteña", "Pop", "Rap", "Regue", "Regeton", "Rock" }));
        cmbGenero.setBorder(null);
        cmbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGeneroActionPerformed(evt);
            }
        });

        lblRuta2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblRuta2.setForeground(new java.awt.Color(255, 255, 255));
        lblRuta2.setText("Ruta:");

        btnSeleccionar2.setBackground(new java.awt.Color(36, 47, 65));
        btnSeleccionar2.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        btnSeleccionar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Open in Window_32px.png"))); // NOI18N
        btnSeleccionar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionar2ActionPerformed(evt);
            }
        });

        txtAlbum.setBackground(new java.awt.Color(36, 47, 65));
        txtAlbum.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtAlbum.setForeground(new java.awt.Color(255, 255, 0));
        txtAlbum.setBorder(null);
        txtAlbum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAlbumFocusLost(evt);
            }
        });
        txtAlbum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAlbumMouseClicked(evt);
            }
        });
        txtAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlbumActionPerformed(evt);
            }
        });
        txtAlbum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAlbumKeyTyped(evt);
            }
        });

        lblGenero4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblGenero4.setForeground(new java.awt.Color(255, 255, 255));
        lblGenero4.setText("Genero:");

        txtArtista.setBackground(new java.awt.Color(36, 47, 65));
        txtArtista.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtArtista.setForeground(new java.awt.Color(255, 255, 0));
        txtArtista.setBorder(null);
        txtArtista.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtArtistaFocusLost(evt);
            }
        });
        txtArtista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtArtistaMouseClicked(evt);
            }
        });
        txtArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArtistaActionPerformed(evt);
            }
        });
        txtArtista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtArtistaKeyTyped(evt);
            }
        });

        txtYear.setBackground(new java.awt.Color(36, 47, 65));
        txtYear.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtYear.setForeground(new java.awt.Color(255, 255, 0));
        txtYear.setBorder(null);
        txtYear.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtYearFocusLost(evt);
            }
        });
        txtYear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtYearMouseClicked(evt);
            }
        });
        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });
        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtYearKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtYearKeyTyped(evt);
            }
        });

        txtRuta.setEditable(false);
        txtRuta.setBackground(new java.awt.Color(36, 47, 65));
        txtRuta.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtRuta.setForeground(new java.awt.Color(255, 255, 0));
        txtRuta.setBorder(null);
        txtRuta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRutaFocusLost(evt);
            }
        });
        txtRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRutaMouseClicked(evt);
            }
        });
        txtRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutaActionPerformed(evt);
            }
        });
        txtRuta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutaKeyTyped(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(36, 47, 65));
        btnAgregar.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add List_32px.png"))); // NOI18N
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Edit File_32px.png"))); // NOI18N
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblArtista2)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addComponent(lblGenero4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(lblAlbum2)
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lblGenero2)
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblRuta2)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(btnSeleccionar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblTitulo2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblGenero4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cmbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblArtista2)
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblAlbum2))
                            .addComponent(txtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblGenero2)
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRuta2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnLimpiar)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(btnSeleccionar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pnlReproduccion.addTab("Lista", jPanel2);

        pnlReproducciendo.setBackground(new java.awt.Color(36, 47, 65));
        pnlReproducciendo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo3.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblTitulo3.setText("Reproducciendo");

        txtCancionReproducciendo.setEditable(false);
        txtCancionReproducciendo.setBackground(new java.awt.Color(255, 255, 255));
        txtCancionReproducciendo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCancionReproducciendo.setForeground(new java.awt.Color(0, 0, 204));
        txtCancionReproducciendo.setBorder(null);
        txtCancionReproducciendo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCancionReproducciendoFocusLost(evt);
            }
        });
        txtCancionReproducciendo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCancionReproducciendoMouseClicked(evt);
            }
        });
        txtCancionReproducciendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancionReproducciendoActionPerformed(evt);
            }
        });
        txtCancionReproducciendo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCancionReproducciendoKeyTyped(evt);
            }
        });

        btnReproducirPause.setBackground(new java.awt.Color(255, 255, 255));
        btnReproducirPause.setForeground(new java.awt.Color(255, 255, 255));
        btnReproducirPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Play_32px.png"))); // NOI18N
        btnReproducirPause.setToolTipText("Reproduccir");
        btnReproducirPause.setBorder(null);
        btnReproducirPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproducirPauseActionPerformed(evt);
            }
        });

        btnIrAnterior.setBackground(new java.awt.Color(255, 255, 255));
        btnIrAnterior.setForeground(new java.awt.Color(255, 255, 255));
        btnIrAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back_32px.png"))); // NOI18N
        btnIrAnterior.setToolTipText("Anterior");
        btnIrAnterior.setBorder(null);
        btnIrAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrAnteriorActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Forward_32px.png"))); // NOI18N
        jButton4.setToolTipText("Siguiente");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/End_32px.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnIrPrimero.setBackground(new java.awt.Color(255, 255, 255));
        btnIrPrimero.setForeground(new java.awt.Color(255, 255, 255));
        btnIrPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Skip to Start_32px.png"))); // NOI18N
        btnIrPrimero.setBorder(null);
        btnIrPrimero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrPrimeroActionPerformed(evt);
            }
        });

        btnIrAnterior1.setBackground(new java.awt.Color(255, 255, 255));
        btnIrAnterior1.setForeground(new java.awt.Color(255, 255, 255));
        btnIrAnterior1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pause_32px.png"))); // NOI18N
        btnIrAnterior1.setToolTipText("Pausa");
        btnIrAnterior1.setBorder(null);
        btnIrAnterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrAnterior1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtCancionReproducciendo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIrPrimero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIrAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(btnIrAnterior1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReproducirPause, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCancionReproducciendo, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                            .addComponent(btnReproducirPause, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnIrAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnIrPrimero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnIrAnterior1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitulo3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlReproducciendo.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 206, 741, 50));

        imagen4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LimpGeneralCopperhead.gif"))); // NOI18N
        pnlReproducciendo.add(imagen4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 140, -1));

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LimpGeneralCopperhead.gif"))); // NOI18N
        pnlReproducciendo.add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, -1));

        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LimpGeneralCopperhead.gif"))); // NOI18N
        pnlReproducciendo.add(imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 210, -1));

        imagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LimpGeneralCopperhead.gif"))); // NOI18N
        pnlReproducciendo.add(imagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 220, -1));

        pnlReproduccion.addTab("Reproducciendo", pnlReproducciendo);

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));

        jLabel7.setText("Copyright © 2017  Miguel Angel Camacho Campos  ");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Copyright © 2017  Miguel Angel Camacho Campos  ");

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Estructura de datos");

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Universidad Técnologica del Norte de Guanajuato");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel12)))))
                .addContainerGap(460, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addGap(247, 247, 247)
                    .addComponent(jLabel7)
                    .addContainerGap(516, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(256, 256, 256)
                    .addComponent(jLabel7)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlReproduccion.addTab("Créditos", jPanel3);

        pnlContenedor.add(pnlReproduccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        btnCerrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Close Window_32px.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pnlContenedor.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 20, 20));

        btnCambiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Animation_32px.png"))); // NOI18N
        btnCambiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambiarMouseClicked(evt);
            }
        });
        btnCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarActionPerformed(evt);
            }
        });
        pnlContenedor.add(btnCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 80, 50, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/music-notes-wallpaper-16215-16714-hd-wallpapers.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        pnlContenedor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 120));

        getContentPane().add(pnlContenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 412));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        listaReproduccion = new ArrayList();

    }//GEN-LAST:event_formWindowOpened
    @SuppressWarnings("unchecked")
    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        int posicion = btnMenu.getX();
        if (posicion > 5) {
            Animacion.Animacion.mover_izquierda(211, 5, 2, 2, btnMenu);
            Animacion.Animacion.mover_izquierda(5, -200, 2, 2, pnlMenu);
            Animacion.Animacion.mover_izquierda(210, 0, 2, 2, pnlReproduccion);
        } else {
            Animacion.Animacion.mover_derecha(5, 210, 2, 2, btnMenu);
            Animacion.Animacion.mover_derecha(-200, 5, 2, 2, pnlMenu);
            Animacion.Animacion.mover_derecha(0, 211, 2, 2, pnlReproduccion);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pnlReproduccion.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTitulo2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTitulo2FocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTitulo2FocusLost

    private void txtTitulo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTitulo2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTitulo2MouseClicked

    private void txtTitulo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitulo2ActionPerformed

    }//GEN-LAST:event_txtTitulo2ActionPerformed

    private void txtTitulo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTitulo2KeyTyped

    }//GEN-LAST:event_txtTitulo2KeyTyped

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        pnlReproduccion.setSelectedIndex(3);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        cancion = new Cancion();
        NodoD nodoNuevo;
        cancion.setTitulo(txtTitulo.getText());
        cancion.setArtista(txtArtista.getText());
        cancion.setAlbum(txtAlbum.getText());
        cancion.setGenero(cmbGenero.getSelectedItem().toString());
        cancion.setYear(Integer.parseInt(txtYear.getText()));
        cancion.setRuta(txtRuta.getText());
        nodoNuevo = new NodoD(cancion);
        lista.insertarOrden(nodoNuevo);
        //Utilizando la APIde java
        listaReproduccion.add(txtTitulo.getText());
        //Ordenar lista
        listaReproduccion.sort(null);
        for (String item : listaReproduccion) {

        }

        txtArtista.setText("");

        lstNombres.setModel(new AbstractListModel<String>() {

            @Override
            public int getSize() {
                return listaReproduccion.size();
            }

            @Override
            public String getElementAt(int i) {
                return listaReproduccion.get(i);
            }
        }
        );
        limpiar();
        JOptionPane.showMessageDialog(this, "La canción " + cancion.getTitulo() + " fue agregada");
        btnAgregar.setEnabled(false);
        pnlReproduccion.setSelectedIndex(0);


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtRutaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutaKeyTyped

    }//GEN-LAST:event_txtRutaKeyTyped

    private void txtRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutaActionPerformed

    }//GEN-LAST:event_txtRutaActionPerformed

    private void txtRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRutaMouseClicked

    }//GEN-LAST:event_txtRutaMouseClicked

    private void txtRutaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRutaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutaFocusLost

    private void txtYearKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyTyped
        textAutoAcompleter = new TextAutoCompleter(txtYear);
        textAutoAcompleter.setCaseSensitive(false);
        textAutoAcompleter.addItem("1997");
        textAutoAcompleter.addItem("1998");
        textAutoAcompleter.addItem("1999");
        textAutoAcompleter.addItem("2000");
        textAutoAcompleter.addItem("2001");
        textAutoAcompleter.addItem("2002");
        textAutoAcompleter.addItem("2003");
        textAutoAcompleter.addItem("2004");
        textAutoAcompleter.addItem("2005");
        textAutoAcompleter.addItem("2006");
        textAutoAcompleter.addItem("2007");
        textAutoAcompleter.addItem("2008");
        textAutoAcompleter.addItem("2009");
        textAutoAcompleter.addItem("2010");
        textAutoAcompleter.addItem("2011");
        textAutoAcompleter.addItem("2012");
        textAutoAcompleter.addItem("2013");
        textAutoAcompleter.addItem("2014");
        textAutoAcompleter.addItem("2016");
        textAutoAcompleter.addItem("2017");
        //Validación
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            getToolkit().beep();
            evt.consume();
        }
        numeroCaracteres = 4;
        if (txtYear.getText().length() >= numeroCaracteres) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Sólo " + numeroCaracteres + " caracteres");
        }
    }//GEN-LAST:event_txtYearKeyTyped

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtYearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtYearMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearMouseClicked

    private void txtYearFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtYearFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearFocusLost

    private void txtArtistaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArtistaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtistaKeyTyped

    private void txtArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtistaActionPerformed

    private void txtArtistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtArtistaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtistaMouseClicked

    private void txtArtistaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtArtistaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArtistaFocusLost

    private void txtAlbumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlbumKeyTyped
        textAutoAcompleter = new TextAutoCompleter(txtAlbum);
        textAutoAcompleter.setCaseSensitive(false);
        textAutoAcompleter.addItem("Yo sin ti");
        textAutoAcompleter.addItem("El olvido");
    }//GEN-LAST:event_txtAlbumKeyTyped

    private void txtAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlbumActionPerformed

    private void txtAlbumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAlbumMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlbumMouseClicked

    private void txtAlbumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlbumFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlbumFocusLost

    private void btnSeleccionar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionar2ActionPerformed
        JFileChooser jfch = new JFileChooser();
        jfch.setFileFilter(filter);
        int op;
        String pathFile = null;
        op = jfch.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            pathFile = jfch.getSelectedFile().getAbsolutePath();
            txtRuta.setText(pathFile);
            btnAgregar.setEnabled(true);
        }
    }//GEN-LAST:event_btnSeleccionar2ActionPerformed

    private void cmbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGeneroActionPerformed

    }//GEN-LAST:event_cmbGeneroActionPerformed

    private void txtTituloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyTyped
        textAutoAcompleter = new TextAutoCompleter(txtTitulo);
        textAutoAcompleter.setCaseSensitive(false);
        textAutoAcompleter.addItem("Hola");
        textAutoAcompleter.addItem("El pollito pio");
        textAutoAcompleter.addItem("Y");
    }//GEN-LAST:event_txtTituloKeyTyped

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        textAutoAcompleter = new TextAutoCompleter(txtTitulo);
        textAutoAcompleter.setCaseSensitive(false);
        textAutoAcompleter.addItem("Hola");
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTituloMouseClicked

    }//GEN-LAST:event_txtTituloMouseClicked

    private void txtTituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTituloFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloFocusLost

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        int resp = JOptionPane.showConfirmDialog(null, "¿Dessea guardar la lista creada?");
        if (JOptionPane.OK_OPTION == resp) {
            String pathFile = "";
            JFileChooser jfc = new JFileChooser();
            int op;
            op = jfc.showSaveDialog(this);
            if (op == JFileChooser.APPROVE_OPTION) {
                pathFile = jfc.getSelectedFile().getAbsolutePath();

                CancionDOM cancionDOM = new CancionDOM();
                cancionDOM.addAll(lista, pathFile);

                JOptionPane.showMessageDialog(null, "Se guardo exitotosamente la lista.");
                this.dispose();
                exitScreen();
            }
        } else {
            this.dispose();
            exitScreen();
        }
        if (myMP3 != null) {
            myMP3.close();
        }


    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        pnlReproduccion.setSelectedIndex(1);
    }//GEN-LAST:event_btnListaActionPerformed

    private void lstNombresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstNombresMouseClicked
        lista.setActual(lstNombres.getSelectedValue());
        mostrarCancion();
    }//GEN-LAST:event_lstNombresMouseClicked

    private void txtCancionReproducciendoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCancionReproducciendoFocusLost

    }//GEN-LAST:event_txtCancionReproducciendoFocusLost

    private void txtCancionReproducciendoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCancionReproducciendoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCancionReproducciendoMouseClicked

    private void txtCancionReproducciendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancionReproducciendoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCancionReproducciendoActionPerformed

    private void txtCancionReproducciendoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCancionReproducciendoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCancionReproducciendoKeyTyped

    private void btnReproducirPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproducirPauseActionPerformed
        myMP3 = new MP3(txtRuta.getText());
        myMP3.play();
        String Ocancion;
        Ocancion = txtTitulo.getText();
        txtCancionReproducciendo.setText(Ocancion);
        timer = new Timer(245, new cronometro());
        timer.start();
    }//GEN-LAST:event_btnReproducirPauseActionPerformed

    private void btnIrPrimeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrPrimeroActionPerformed
        lista.irPrimero();
        mostrarCancion();
    }//GEN-LAST:event_btnIrPrimeroActionPerformed

    private void btnIrAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrAnteriorActionPerformed
        lista.irAnterior();
        mostrarCancion();
    }//GEN-LAST:event_btnIrAnteriorActionPerformed

    private void btnLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLista1ActionPerformed
        pnlReproduccion.setSelectedIndex(2);
    }//GEN-LAST:event_btnLista1ActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        if (lstNombres.getSelectedIndex() != -1) {
            if (lista.eliminar()) {
                JOptionPane.showMessageDialog(this, "Canción eliminada");
            } else {
                JOptionPane.showMessageDialog(this, "No se puede acompletar la accion");
            }
            sacarLlista();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "selecciona alguna canción");
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        lista.irSiguiente();
        mostrarCancion();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        lista.irUltimo();
        mostrarCancion();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnAbrir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrir1ActionPerformed
        lista = new ListaCanciones();
        List<Cancion> canciones;
        Cancion cancion;
        CancionDOM cancionDOM = new CancionDOM();
        String pathFile = "";
        JFileChooser jfc = new JFileChooser();
        jfc.setFileFilter(filterOpen);
        int op;
        op = jfc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            pathFile = jfc.getSelectedFile().getAbsolutePath();
            canciones = cancionDOM.getAll(pathFile);
            for (int i = 0; i < canciones.size(); i++) {
                cancion = canciones.get(i);
                lista.insertarOrden(new NodoD(cancion));
            }
        }
    }//GEN-LAST:event_btnAbrir1ActionPerformed

    private void txtYearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearKeyReleased

    private void btnCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarActionPerformed

        imagen1.setIcon(new ImageIcon(getClass().getResource("../img/HatefulIllGrayling-small.gif")));
        imagen2.setIcon(new ImageIcon(getClass().getResource("../img/HatefulIllGrayling-small.gif")));
        imagen3.setIcon(new ImageIcon(getClass().getResource("../img/HatefulIllGrayling-small.gif")));
        imagen4.setIcon(new ImageIcon(getClass().getResource("../img/HatefulIllGrayling-small.gif")));

    }//GEN-LAST:event_btnCambiarActionPerformed

    private void btnCambiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambiarMouseClicked

    }//GEN-LAST:event_btnCambiarMouseClicked

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        try {

            lista.getActual().getDatos().setTitulo(txtTitulo.getText());
            lista.getActual().getDatos().setArtista(txtArtista.getText());
            lista.getActual().getDatos().setAlbum(txtAlbum.getText());
            lista.getActual().getDatos().setYear(Integer.parseInt(txtYear.getText()));
            lista.getActual().getDatos().setGenero(cmbGenero.getSelectedItem().toString());
            lista.getActual().getDatos().setRuta(txtRuta.getText());

            JOptionPane.showMessageDialog(this, "Cambio Exitoso");
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "No se puede editar por el momento");
        }
        sacarLlista();
        limpiar();
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void lstNombres1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstNombres1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lstNombres1MouseClicked

    private void btnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar1ActionPerformed
        pnlReproduccion.setSelectedIndex(2);
        myMP3 = new MP3(txtRuta.getText());
        myMP3.play();
        String Ocancion;
        Ocancion = txtTitulo.getText();
        txtCancionReproducciendo.setText(Ocancion);
        timer = new Timer(245, new cronometro());
        timer.start();
    }//GEN-LAST:event_btnBorrar1ActionPerformed

    private void btnIrAnterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrAnterior1ActionPerformed
      myMP3.close();
    }//GEN-LAST:event_btnIrAnterior1ActionPerformed

    private void limpiar() {
        txtAlbum.setText("");
        txtArtista.setText("");
        txtRuta.setText("");
        txtTitulo.setText("");
        txtYear.setText("");
        cmbGenero.setSelectedIndex(0);
    }

    private void mostrarCancion() {
        try {
            Cancion cancion = lista.getActual().getDatos();
            if (lista.getActual() != null) {
                txtAlbum.setText(cancion.getAlbum());
                txtArtista.setText(cancion.getArtista());
                txtRuta.setText(cancion.getRuta());
                txtTitulo.setText(cancion.getTitulo());
                txtYear.setText("" + cancion.getYear());
                cmbGenero.setSelectedItem(cancion.getGenero());
            }
        } catch (NullPointerException e) {
            //JOptionPane.showMessageDialog(this, "No se puede mostrar la imagen");
        }
    }

    public class cronometro implements ActionListener {

        public void actionPerformed(ActionEvent evt) {

            String nuevo_texto = txtCancionReproducciendo.getText().substring(1) + txtCancionReproducciendo.getText().substring(0, 1);
            txtCancionReproducciendo.setText(nuevo_texto);
        }
    }

    public void ponerCancionLista() {
        lstNombres.setSelectedValue(txtTitulo.getText(), true);
    }

    public void sacarLlista() {

        lstNombres.setModel(new AbstractListModel<String>() {
            @Override
            public int getSize() {
                return lista.recorrerLista();
            }

            @Override
            public String getElementAt(int i) {

                return lista.sacarCancion(i);
            }

        });
    }

    public final void exitScreen() {
        JFrame f = new JFrame(); //creates jframe f
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize(); //this is your screen size
        f.setUndecorated(true); //removes the surrounding border
        f.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
        ImageIcon image = new ImageIcon(Principal.class.getResource("/img/tumblr_inline_mq1nopjB591qz4rgp.png")); //imports the image
        JLabel lbl = new JLabel(image); //puts the image into a jlabel
        f.getContentPane().add(lbl); //puts label inside the jframe
        f.setSize(image.getIconWidth(), image.getIconHeight()); //gets h and w of image and sets jframe to the size
        int x = this.getX(); //These two lines are the dimensions
        int y = this.getY();//of the center of the screen
        f.setLocation(x, y); //sets the location of the jframe
        f.setVisible(true); //makes the jframe visible
        long initial = System.currentTimeMillis();
        while (System.currentTimeMillis() - initial < 1500) {
            if (System.currentTimeMillis() % 50 == 0) {
                f.update(f.getGraphics());
            }
        }
        f.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    private Timer timer;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir1;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBorrar1;
    private javax.swing.JButton btnCambiar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnIrAnterior;
    private javax.swing.JButton btnIrAnterior1;
    private javax.swing.JButton btnIrPrimero;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnLista1;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReproducirPause;
    private javax.swing.JToggleButton btnSeleccionar2;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JLabel imagen3;
    private javax.swing.JLabel imagen4;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAlbum2;
    private javax.swing.JLabel lblArtista2;
    private javax.swing.JLabel lblGenero2;
    private javax.swing.JLabel lblGenero4;
    private javax.swing.JLabel lblRuta2;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JLabel lblTitulo3;
    private javax.swing.JList<String> lstNombres;
    private javax.swing.JList<String> lstNombres1;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlMiMusica;
    private javax.swing.JPanel pnlMiMusica1;
    private javax.swing.JPanel pnlReproducciendo;
    private javax.swing.JTabbedPane pnlReproduccion;
    private javax.swing.JTextField txtAlbum;
    private javax.swing.JTextField txtArtista;
    private javax.swing.JTextField txtCancionReproducciendo;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtTitulo2;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
